래더 게임을 위한 대기큐 만들기
august-thirty-first/backend pull request #56
Opened 2023-08-10 07:31 UTC by flowjiyun

## 관련 이슈
- #49 

## 요약
- 래더게임의 대기 큐 생성 및 매칭 시스템 구현
<br><br>

## 작업내용
- joinQueue 이벤트 발생시 대기 큐에 소켓을 넣어서 매칭을 대기함
- room 번호는 소켓의 default room 번호인 소켓 아이디를 사용함
- 소켓 연결 끊어 졌을때 큐에서 제거함
<br><br>

## 참고사항

<br><br>

2023-08-10 08:59 UTC, yoonkiung requested changes
game.gateway.ts파일에서 49번째줄 ===이 아니라 >= 로 바꿔도 좋을 것 같습니다

2023-08-11 00:41 UTC, jari46 commented on nestjs/src/socket/game/game.gateway.ts
> +      if (frontSocket.id === backSocket.id) {
언제 여기에 들어올까요?

2023-08-11 01:02 UTC, flowjiyun commented on nestjs/src/socket/game/game.gateway.ts
> +      if (frontSocket.id === backSocket.id) {
대기열 페이지에서 뒤로가기 후 다시 앞으로 가기 했을 때 동일한 소켓이 대기열에 추가되는 것을 방지하고자 해당 코드를 작성하였습니다

2023-08-11 01:14 UTC, yoonkiung approved these changes

2023-08-11 01:17 UTC, merged